### real
GET https://api.trakteer.id/v1/public/supports?limit=10
key: {{$dotenv TRAKTEER_API_KEY}}

### self
GET http://localhost:6883/supports

### self with key
GET http://localhost:6883/supports
key: trapi-abc
